<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>HJ_Inc_Backup</AssemblyName>
    <RootNamespace>HJ_Inc_Backup</RootNamespace>
    <Version>1.0.0</Version>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>j5lmr.ico</ApplicationIcon>
    <PackageIcon>j5lmr.jpg</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="j5lmr.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Downloads\j5lmr.jpg">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Ookii.Dialogs.Wpf" Version="5.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HJ_Inc_Backup.Core\HJ_Inc_Backup.Core.csproj" />
  </ItemGroup>

</Project>